AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Aws Servless Cloud Native Java Restful Api

  Trabalho para entrega da disciplina de AWS Servless.

  '
Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    Environment:
      Variables:
        TABLE_NAME:
          Ref: TripTable
        ENDPOINT_OVERRIDE: ''
Resources:
  CreateTripRecordFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://fiap-aws-servless-bruno-335369/706195ad05c27538b4a88f591ea36364
      Handler: br.com.fiap.handler.CreateTripRecord::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TripTable
      Events:
        CreateTripRecord:
          Type: Api
          Properties:
            Path: /trip
            Method: post
  GetTripRecordsByPeriodFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://fiap-aws-servless-bruno-335369/706195ad05c27538b4a88f591ea36364
      Handler: br.com.iwe.handler.GetTripRecordsByPeriod::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TripTable
      Events:
        GetStudyRecordsByPeriod:
          Type: Api
          Properties:
            Path: /trips
            Method: get
            RequestParameters:
            - method.request.querystring.start
            - method.request.querystring.end
  # ----
#  GetStudyRecordsByTagFunction:
#    Type: AWS::Serverless::Function
#    Properties:
#      CodeUri: s3://fiap-aws-servless-bruno-335369/706195ad05c27538b4a88f591ea36364
#      Handler: br.com.iwe.handler.GetStudyRecordsByTag::handleRequest
#      Runtime: java8
#      Policies:
#      - DynamoDBCrudPolicy:
#          TableName:
#            Ref: StudyTable
#      Events:
#        GetStudyRecordsByTag:
#          Type: Api
#          Properties:
#            Path: /study/{topic}/findByTag
#            Method: get
#            RequestParameters:
#            - method.request.querystring.tag
  # ----
#  GetStudyRecordsByIsConsumedFunction:
#    Type: AWS::Serverless::Function
#    Properties:
#      CodeUri: s3://fiap-aws-servless-bruno-335369/706195ad05c27538b4a88f591ea36364
#      Handler: br.com.iwe.handler.GetStudyRecordsByIsConsumed::handleRequest
#      Runtime: java8
#      Policies:
#      - DynamoDBCrudPolicy:
#          TableName:
#            Ref: StudyTable
#      Events:
#        GetStudyRecordsByIsConsumed:
#          Type: Api
#          Properties:
#            Path: /study/{topic}/findByIsConsumed
#            Method: get
#            RequestParameters:
#            - method.request.querystring.isconsumed
  TripTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: trip
      AttributeDefinitions:
      - AttributeName: country
        AttributeType: S
      - AttributeName: date
        AttributeType: S
      - AttributeName: city
        AttributeType: S
      - AttributeName: reason
        AttributeType: S
      KeySchema:
      - AttributeName: country
        KeyType: HASH
      - AttributeName: date
        KeyType: RANGE
      LocalSecondaryIndexes:
      - IndexName: cityIdx
        KeySchema:
        - AttributeName: country
          KeyType: HASH
        - AttributeName: city
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
Outputs:
  CreateTripRecordFunction:
    Description: CreateTripRecord Lambda Function ARN
    Value:
      Fn::GetAtt:
      - CreateTripRecordFunction
      - Arn
  GetTripRecordsByPeriodFunction:
    Description: GetTripRecordsByPeriod Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetTripRecordsByPeriodFunction
      - Arn
#  GetStudyRecordsByTagFunction:
#    Description: GetStudyRecordsByTag Lambda Function ARN
#    Value:
#      Fn::GetAtt:
#      - GetStudyRecordsByTagFunction
#      - Arn
#  GetStudyRecordsByIsConsumedFunction:
#    Description: GetStudyRecordsByIsConsumed Lambda Function ARN
#    Value:
#      Fn::GetAtt:
#      - GetStudyRecordsByIsConsumedFunction
#      - Arn